version: 2.1
aliases:
  - &node_image
    docker:
      - image: circleci/node:12.16

  - &working_directory
    working_directory: ~/workspace

jobs:
  build:
    <<: *node_image
    <<: *working_directory

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

wordflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
